### PR TITLE
WIP [DON'T MERGE]: Streaming support

### PR DESCRIPTION
**Pull request by zoldar**
This is my first stab at this feature. The code is horrible but I want to make it work at all first. On yesterday evening I've tried to debug an issue with streaming request hanging until timeout. I'm probably doing something borderline idiotic in the message passing part because I don't see anything reaching `erl_input` function in the C wrapper. I will also have to up my game with debugging techniques because currently I rely on a typical print pased approach ;) If anyone could have a look at this in their spare time, I would be grateful. /cc @puzza007 @aerosol

### CODE REVIEW

**Comment by aerosol** [comment]
:heart_eyes_cat:

**Comment by puzza007** [comment]
Nice! Looks super promising! Any idea if it could be generalised for http2?

**Comment by zoldar** [comment]
@puzza007 first I would have to read up on http2 ;)

**Comment by puzza007** [comment]
Time flies! I'm doing a tidy up. Feel free to reopen 😄

**Pull request closed without merging**
