### PR TITLE
add support for client certificates

### PR DESCRIPTION
**Pull request by dlesl**

### CODE REVIEW

**Comment by dlesl** [comment]
I rebased on your fix-unit-tests branch, but couldn't get the tests involving specifying certificates to pass on CI (including the existing self-issued certificate test, which makes me think it's unrelated to my changes). I couldn't reproduce locally so I just gave up and used `nix` on travis which seems to work. Maybe something to do with openssl on travis' version of ubuntu?

**Comment by puzza007** [comment]
Oh hey that's nice! Yeah I've not had the time to find out why that particular test was broken in CI. Works for me locally. Thanks for the feature, fixing the test and forcing me to finally check out Nix! 👍

**Comment by puzza007** [comment]
Let me know if you'd like a new version pushed to hex.pm.

**Review by puzza007 — APPROVED** [review]

**Comment by dlesl** [comment]
That would be great, I see that v1.0.0 is on the way. Thanks for the library!

**Comment by puzza007** [comment]
Done https://hex.pm/packages/katipo/1.0.0. Thanks again for your contribution!

**Pull request merged**
