### PR TITLE
feat: add HTTP Negotiate (SPNEGO) authentication

### PR DESCRIPTION
**Pull request by macasado86**
feat: add HTTP Negotiate (SPNEGO) authentication

### CODE REVIEW

**Comment by puzza007** [comment]
Thanks for this! I'll merge it soon, I just need to set up my local development environment or fix https://github.com/puzza007/katipo/issues/128 😄

**Comment by puzza007** [comment]
Thanks again! Merged in https://github.com/puzza007/katipo/pull/130. I'll release to hex soon.

**Comment by puzza007** [comment]
https://hex.pm/packages/katipo/1.0.3

**Comment by macasado86** [comment]
Thank you very much!

**Pull request closed without merging**
